spring:
  application:
    name: zuul-server
    
server:
  port: 8888
  
zuul:
  routes:
     sop:
       path: /sop
       strip-prefix: false
       service-id: sop-server
   
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true      
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    